var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sb5-to._.js")
R.c("server/chunks/ssr/1_sk_0f27uua._.js")
R.c("server/chunks/ssr/1_sk_next_dist_esm_build_templates_app-page_14gnf-x.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ezf1t._.js")
R.c("server/chunks/ssr/1_sk_next_dist_1ihlua4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hdnwl3._.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_0mfue6u._.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_builtin_forbidden_1i97i_c.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_builtin_unauthorized_189jfi-.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_builtin_global-error_1ehd18_.js")
R.c("server/chunks/ssr/1uf8_workspace_sakhalinstay__next-internal_server_app_admin_page_actions_1hr_c8a.js")
R.m(47034)
module.exports=R.m(47034).exports
