var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/help/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__17f0gq8._.js")
R.c("server/chunks/ssr/1_sk_0f27uua._.js")
R.c("server/chunks/ssr/1_sk_next_dist_esm_build_templates_app-page_1pvnwai.js")
R.c("server/chunks/ssr/[root-of-the-server]__06ezf1t._.js")
R.c("server/chunks/ssr/1_sk_next_dist_1ihlua4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hdnwl3._.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_0mfue6u._.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_builtin_forbidden_1i97i_c.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_builtin_unauthorized_189jfi-.js")
R.c("server/chunks/ssr/1_sk_next_dist_client_components_builtin_global-error_1ehd18_.js")
R.c("server/chunks/ssr/1uf8_workspace_sakhalinstay__next-internal_server_app_help_page_actions_0v_dw32.js")
R.m(36758)
module.exports=R.m(36758).exports
